version: '3.9'

services:
  main-app:
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: main-app
    ports:
      - "8000:8000"
    env_file:
      - ../.env
    volumes:
      - ..:/app/